Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,10 +21,17 @@ jobs:
         run: |
           pip install mlflow pandas scikit-learn joblib
 
-      - name: Run MLflow Project
+      - name: Run MLflow Project (Training)
         run: |
-          export MLFLOW_TRACKING_URI=sqlite:///mlflow.db
           mlflow run MLProject --env-manager local
+
+      - name: Validate Model Folder
+        run: |
+          if [ ! -f model/model.pkl ]; then
+            echo "❌ Model file not found"
+            exit 1
+          fi
+          echo "✅ Model file exists"
 
       - name: Login to Docker Hub
         uses: docker/login-action@v3
@@ -35,7 +42,7 @@ jobs:
       - name: Build and Push Docker Image
         run: |
           mlflow models build-docker \
-            -m random_forest_model \
+            -m model \
             -n "${{ secrets.DOCKER_USERNAME }}/heart-disease-ci:latest" \
             --install-mlflow
 
